
# this is a very simple makefile for modules
TOP_DIR=../..

# define the module name - make sure name is max 8 characters
MODULE_NAME=tiny8086
MODULE_OBJS=8086tiny.o

MODULE_CFLAGS += -fsigned-char -DNO_GRAPHICS

# include modules environment
include $(TOP_DIR)/modules/Makefile.modules
