#include "all_features.h"
/* Can't Be Implemented */

#define FEATURE_DIGITAL_ZOOM_SHORTCUT
#define FEATURE_LV_3RD_PARTY_FLASH
#define FEATURE_FLASH_TWEAKS
#define FEATURE_EYEFI_TRICKS

#define FEATURE_DIGITAL_ZOOM_SHORTCUT_1300D

#define DEBUG_TASK_HOOK


#define FEATURE_INTERMEDIATE_ISO_PHOTO_DISPLAY

//#undef FEATURE_FLEXINFO
#define FEATURE_FLEXINFO

//#undef FEATURE_SHOW_TASKS
//#undef FEATURE_SHOW_CPU_USAGE
//#undef FEATURE_SHOW_GUI_EVENTS

#undef FEATURE_SHOW_IMAGE_BUFFERS_INFO
#undef FEATURE_SHOW_EDMAC_INFO

//#undef CONFIG_TSKMON

#define FEATURE_CUSTOM_MODES

// UNDEFINE because qemu locks.
#undef FEATURE_EXPO_APERTURE
#undef FEATURE_EXPO_LOCK
#undef FEATURE_EXPO_PRESET
#undef FEATURE_HDR_BRACKETING
#undef FEATURE_FOLLOW_FOCUS
#undef FEATURE_RACK_FOCUS
#undef FEATURE_FOCUS_STACKING
#undef FEATURE_LV_ZOOM_SETTINGS
#undef FEATURE_LV_ZOOM_SHARP_CONTRAST
#undef FEATURE_LV_ZOOM_AUTO_EXPOSURE
#undef FEATURE_LV_FOCUS_BOX_FAST
#undef FEATURE_LV_FOCUS_BOX_SNAP
#undef FEATURE_POWERSAVE_LIVEVIEW